image: docker:latest

services:
  - docker:dind

stages:
  - build
  - deploy

before_script:
  - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD 

build_image:
  stage: build
  script:
    - docker build -t node .
    - docker tag node:latest bruunoosiilva/gitlab-node-test:latest
    - docker push bruunoosiilva/gitlab-node-test:latest
    
deploy:
  stage: deploy
  tags: 
    - deploy-runner
  script:
    - echo "Deploy started now"
    - docker-compose up --build -d
    - docker ps -a
    - echo "Deploy has been finished"
